# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

assign_issues:
  - Yuan325
  - duwenxin99
  - anubhav756
  - twishabansal
  - dishaprakash
assign_issues_by:
  - labels:
    - 'product: alloydb'
    to:
    - 'googleapis/toolbox-alloydb-team'
  - labels:
    - 'product: bigquery'
    to:
    - 'googleapis/toolbox-bigquery-team'
  - labels:
    - 'product: bigtable'
    to:
    - 'googleapis/toolbox-bigtable-team'
  - labels:
    - 'product: mssql'
    to:
    - 'googleapis/toolbox-cloud-sql-mssql-team'
  - labels:
    - 'product: mysql'
    to:
    - 'googleapis/toolbox-cloud-sql-mysql-team'
  - labels:
    - 'product: postgres'
    to:
    - 'googleapis/toolbox-cloud-sql-postgres-team'
  - labels:
    - 'product: dataplex'
    to:
    - 'googleapis/toolbox-dataplex-team'
  - labels:
    - 'product: firestore'
    to:
    - 'googleapis/toolbox-firestore-team'
  - labels:
    - 'product: looker'
    to:
    - 'googleapis/toolbox-looker-team'
  - labels:
    - 'product: spanner'
    to:
    - 'googleapis/toolbox-spanner-team'
assign_prs:
  - Yuan325
  - duwenxin99
assign_prs_by:
  - labels:
    - 'product: alloydb'
    to:
    - 'googleapis/toolbox-alloydb-team'
  - labels:
    - 'product: bigquery'
    to:
    - 'googleapis/toolbox-bigquery-team'
  - labels:
    - 'product: bigtable'
    to:
    - 'googleapis/toolbox-bigtable-team'
  - labels:
    - 'product: mssql'
    to:
    - 'googleapis/toolbox-cloud-sql-mssql-team'
  - labels:
    - 'product: mysql'
    to:
    - 'googleapis/toolbox-cloud-sql-mysql-team'
  - labels:
    - 'product: postgres'
    to:
    - 'googleapis/toolbox-cloud-sql-postgres-team'
  - labels:
    - 'product: dataplex'
    to:
    - 'googleapis/toolbox-dataplex-team'
  - labels:
    - 'product: firestore'
    to:
    - 'googleapis/toolbox-firestore-team'
  - labels:
    - 'product: looker'
    to:
    - 'googleapis/toolbox-looker-team'
  - labels:
    - 'product: spanner'
    to:
    - 'googleapis/toolbox-spanner-team'

